"""Single place for the text shown by /commands (keep in sync with BOT_COMMANDS.md)."""


def telegram_full_command_help() -> str:
    return (
        "📋 Sapmed 봇 — 명령 모음\n"
        "\n"
        "기본\n"
        "· /start · /help — 짧은 안내\n"
        "· /commands — 지금 보는 전체 목록\n"
        "· /ping — pong (살아 있음 확인)\n"
        "\n"
        "일정·동기화\n"
        "· /schedule — SMU 포털 → 노션 동기화 (서브프로세스, 1~수 분)\n"
        "· /today — 오늘 시간표 (로컬 schedule.json, JST)\n"
        "· /tomorrow — 내일\n"
        "· /syncstatus — 마지막 성공 동기화 시각 · schedule.json 행 수\n"
        "\n"
        "준비물 ↔ 노션\n"
        "· /pack — 목록 (노션 to-do 와 동기)\n"
        "· /pack 2 또는 /pack 2 4 5 — 번호 토글 (여러 개 가능, 응답 = 갱신 목록)\n"
        "· /pack clear — 전체 체크 해제\n"
        "· /pack setup — 노션에 블록 다시 붙이기 (중복 가능)\n"
        "\n"
        "AI 질문 (Gemini + DeepSeek)\n"
        "· /gemini — 항상 Google Gemini\n"
        "· /deepseek 또는 /ds — 항상 DeepSeek\n"
        "· /g /ask — 이 채팅 기본 엔진 (/provider)\n"
        "· fast|think|pro — 일회 모드 (각 명령 앞에 붙이기)\n"
        "· /provider (/p) — 기본 엔진 gemini | deepseek\n"
        "· /gemini_default (/gset) — 이 채팅 기본 모드\n"
        "\n"
        "BotFather 에 메뉴 넣기: 저장소의 BOT_COMMANDS.md 블록 복사"
    )
